// Mocks generated by Mockito 5.3.2 from annotations
// in number_trivia_app/test/features/favorite_trivia/data/repositories/favorite_number_trivia_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:number_trivia_app/features/favorite_trivia/favorite_trivia.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoriteNumberTriviaModel_0 extends _i1.SmartFake
    implements _i2.FavoriteNumberTriviaModel {
  _FakeFavoriteNumberTriviaModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoriteNumberTriviaLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteNumberTriviaLocalDataSource extends _i1.Mock
    implements _i2.FavoriteNumberTriviaLocalDataSource {
  @override
  _i3.Future<List<_i2.FavoriteNumberTriviaModel>> getFavoriteNumberTrivia() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteNumberTrivia,
          [],
        ),
        returnValue: _i3.Future<List<_i2.FavoriteNumberTriviaModel>>.value(
            <_i2.FavoriteNumberTriviaModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i2.FavoriteNumberTriviaModel>>.value(
                <_i2.FavoriteNumberTriviaModel>[]),
      ) as _i3.Future<List<_i2.FavoriteNumberTriviaModel>>);
  @override
  _i3.Future<_i2.FavoriteNumberTriviaModel> removeFavoriteNumberTrivia(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavoriteNumberTrivia,
          [id],
        ),
        returnValue: _i3.Future<_i2.FavoriteNumberTriviaModel>.value(
            _FakeFavoriteNumberTriviaModel_0(
          this,
          Invocation.method(
            #removeFavoriteNumberTrivia,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FavoriteNumberTriviaModel>.value(
                _FakeFavoriteNumberTriviaModel_0(
          this,
          Invocation.method(
            #removeFavoriteNumberTrivia,
            [id],
          ),
        )),
      ) as _i3.Future<_i2.FavoriteNumberTriviaModel>);
}
