// Mocks generated by Mockito 5.3.2 from annotations
// in number_trivia_app/test/features/favorite_trivia/data/datasources/favorite_date_trivia_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:number_trivia_app/features/favorite_trivia/favorite_trivia.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoriteDateTriviaModel_0 extends _i1.SmartFake
    implements _i2.FavoriteDateTriviaModel {
  _FakeFavoriteDateTriviaModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoriteDateTriviaLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteDateTriviaLocalDataSource extends _i1.Mock
    implements _i2.FavoriteDateTriviaLocalDataSource {
  @override
  _i3.Future<List<_i2.FavoriteDateTriviaModel>> getFavoriteDateTrivia() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteDateTrivia,
          [],
        ),
        returnValue: _i3.Future<List<_i2.FavoriteDateTriviaModel>>.value(
            <_i2.FavoriteDateTriviaModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i2.FavoriteDateTriviaModel>>.value(
                <_i2.FavoriteDateTriviaModel>[]),
      ) as _i3.Future<List<_i2.FavoriteDateTriviaModel>>);
  @override
  _i3.Future<_i2.FavoriteDateTriviaModel> removeFavoriteDateTrivia(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavoriteDateTrivia,
          [id],
        ),
        returnValue: _i3.Future<_i2.FavoriteDateTriviaModel>.value(
            _FakeFavoriteDateTriviaModel_0(
          this,
          Invocation.method(
            #removeFavoriteDateTrivia,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.FavoriteDateTriviaModel>.value(
                _FakeFavoriteDateTriviaModel_0(
          this,
          Invocation.method(
            #removeFavoriteDateTrivia,
            [id],
          ),
        )),
      ) as _i3.Future<_i2.FavoriteDateTriviaModel>);
}
